using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Microsoft.Extensions.Logging;
using STEM.Application.Interfaces;
using STEM.Core.Entities.Simulations;

namespace STEM.Infrastructure.Services.Wokwi;

/// <summary>
/// Triển khai IWokwiService: parse/serialize diagram.json, validate,
/// sinh Python code mock GPIO và liệt kê catalog component nội bộ.
/// Không phụ thuộc API ngoài — toàn bộ chạy in-process.
/// </summary>
public class WokwiService : IWokwiService
{
    private readonly ILogger<WokwiService> _logger;
    private readonly JsonSerializerOptions _jsonOptions;

    // Catalog tĩnh — khởi tạo một lần khi app start.
    private static readonly IReadOnlyDictionary<string, ComponentMeta> _catalog =
        BuildCatalog();

    public WokwiService(ILogger<WokwiService> logger)
    {
        _logger = logger;
        _jsonOptions = new JsonSerializerOptions
        {
            PropertyNamingPolicy         = JsonNamingPolicy.CamelCase,
            WriteIndented                = true,
            DefaultIgnoreCondition       = JsonIgnoreCondition.WhenWritingNull,
            PropertyNameCaseInsensitive  = true   // linh hoạt khi nhận JSON từ FE
        };
    }

    // ── Parse / Serialize ─────────────────────────────────────────────────────

    public WokwiDiagram ParseDiagram(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<WokwiDiagram>(json, _jsonOptions)
                   ?? throw new InvalidOperationException("Diagram JSON parse trả về null.");
        }
        catch (JsonException ex)
        {
            _logger.LogError(ex, "Lỗi parse Wokwi diagram JSON.");
            throw;
        }
    }

    public string SerializeDiagram(WokwiDiagram diagram)
    {
        return JsonSerializer.Serialize(diagram, _jsonOptions);
    }

    // ── Validate ──────────────────────────────────────────────────────────────

    public (bool IsValid, List<string> Errors) ValidateDiagram(WokwiDiagram diagram)
    {
        var errors  = new List<string>();
        var seenIds = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

        foreach (var part in diagram.Parts)
        {
            // 1. Id không được rỗng
            if (string.IsNullOrWhiteSpace(part.Id))
            {
                errors.Add($"Một part có Type '{part.Type}' bị thiếu Id.");
                continue;
            }

            // 2. Id không được trùng
            if (!seenIds.Add(part.Id))
            {
                errors.Add($"Id '{part.Id}' bị trùng trong diagram.");
            }

            // 3. Type phải có trong catalog
            if (!_catalog.ContainsKey(part.Type))
            {
                errors.Add(
                    $"Component type '{part.Type}' (Id: '{part.Id}') " +
                    $"không được hỗ trợ. Các type hợp lệ: {string.Join(", ", _catalog.Keys)}.");
            }
        }

        return (errors.Count == 0, errors);
    }

    // ── Python Code Generation ────────────────────────────────────────────────

    public string GeneratePythonCode(WokwiDiagram diagram)
    {
        var types     = diagram.Parts.Select(p => p.Type).ToHashSet(StringComparer.OrdinalIgnoreCase);
        bool hasLed    = types.Contains("wokwi-led");
        bool hasButton = types.Contains("wokwi-pushbutton");
        bool hasDht22  = types.Contains("wokwi-dht22");
        bool hasDht11  = types.Contains("wokwi-dht11");
        bool hasDht    = hasDht22 || hasDht11;
        bool hasBuzzer = types.Contains("wokwi-buzzer");
        bool hasLcd    = types.Contains("wokwi-lcd1602");
        bool hasPot    = types.Contains("wokwi-potentiometer");
        bool hasServo  = types.Contains("wokwi-servo");

        var sb = new StringBuilder();

        // ── File header ──────────────────────────────────────────────────────
        sb.AppendLine("# ============================================================");
        sb.AppendLine("# StemFlow Virtual Lab — auto-generated by WokwiService");
        sb.AppendLine("# Chạy trong Pyodide (browser WASM). Không cần phần cứng thật.");
        sb.AppendLine("# ============================================================");
        sb.AppendLine();
        sb.AppendLine("import time");
        sb.AppendLine("import random");
        sb.AppendLine();

        // ── Mock RPi.GPIO ────────────────────────────────────────────────────
        sb.AppendLine("# ── Mock RPi.GPIO ──────────────────────────────────────────");
        sb.AppendLine("class _GPIO:");
        sb.AppendLine("    BCM = 11; BOARD = 10; IN = 1; OUT = 0; HIGH = 1; LOW = 0");
        sb.AppendLine("    _state: dict = {}");
        sb.AppendLine("    def setmode(self, mode): pass");
        sb.AppendLine("    def setwarnings(self, flag): pass");
        sb.AppendLine("    def setup(self, pin, mode, initial=0):");
        sb.AppendLine("        self._state[pin] = initial");
        sb.AppendLine("    def output(self, pin, value):");
        sb.AppendLine("        self._state[pin] = value");
        sb.AppendLine("        label = 'HIGH' if value else 'LOW'");
        sb.AppendLine("        print(f'[GPIO] pin {pin} → {label}')");
        sb.AppendLine("    def input(self, pin):");
        sb.AppendLine("        return self._state.get(pin, 0)");
        sb.AppendLine("    def cleanup(self):");
        sb.AppendLine("        self._state.clear()");
        sb.AppendLine("        print('[GPIO] cleanup done.')");
        sb.AppendLine("GPIO = _GPIO()");
        sb.AppendLine();

        // ── Mock Adafruit_DHT ────────────────────────────────────────────────
        if (hasDht)
        {
            sb.AppendLine("# ── Mock Adafruit_DHT ──────────────────────────────────────");
            sb.AppendLine("class _Adafruit_DHT:");
            sb.AppendLine("    DHT22 = 22");
            sb.AppendLine("    DHT11 = 11");
            sb.AppendLine("    def read_retry(self, sensor, pin):");
            sb.AppendLine("        humidity    = round(random.uniform(40.0, 80.0), 1)");
            sb.AppendLine("        temperature = round(random.uniform(20.0, 35.0), 1)");
            sb.AppendLine("        return humidity, temperature");
            sb.AppendLine("Adafruit_DHT = _Adafruit_DHT()");
            sb.AppendLine();
        }

        // ── Mock LCD1602 ─────────────────────────────────────────────────────
        if (hasLcd)
        {
            sb.AppendLine("# ── Mock LCD1602 ───────────────────────────────────────────");
            sb.AppendLine("class _LCD:");
            sb.AppendLine("    def __init__(self):");
            sb.AppendLine("        self._lines = ['', '']");
            sb.AppendLine("    def clear(self):");
            sb.AppendLine("        self._lines = ['', '']");
            sb.AppendLine("        print('[LCD] cleared')");
            sb.AppendLine("    def cursor_pos(self, row, col): pass");
            sb.AppendLine("    def write_string(self, text):");
            sb.AppendLine("        self._lines[0] = text");
            sb.AppendLine("        print(f'[LCD] {text}')");
            sb.AppendLine("lcd = _LCD()");
            sb.AppendLine();
        }

        // ── Pin constants ────────────────────────────────────────────────────
        sb.AppendLine("# ── Pin constants (BCM numbering) ──────────────────────────");
        if (hasLed)    sb.AppendLine("LED_PIN    = 18");
        if (hasButton) sb.AppendLine("BTN_PIN    = 17");
        if (hasDht)
        {
            string sensor = hasDht22 ? "DHT22" : "DHT11";
            sb.AppendLine($"DHT_PIN    = 4");
            sb.AppendLine($"DHT_SENSOR = Adafruit_DHT.{sensor}");
        }
        if (hasBuzzer) sb.AppendLine("BUZZER_PIN = 27");
        if (hasPot)    sb.AppendLine("POT_PIN    = 24   # đọc qua ADC (giá trị mock 0–1023)");
        if (hasServo)  sb.AppendLine("SERVO_PIN  = 25");
        sb.AppendLine();

        // ── GPIO setup ───────────────────────────────────────────────────────
        sb.AppendLine("# ── GPIO setup ─────────────────────────────────────────────");
        sb.AppendLine("GPIO.setmode(GPIO.BCM)");
        sb.AppendLine("GPIO.setwarnings(False)");
        if (hasLed)    sb.AppendLine("GPIO.setup(LED_PIN,    GPIO.OUT, initial=GPIO.LOW)");
        if (hasButton) sb.AppendLine("GPIO.setup(BTN_PIN,    GPIO.IN)");
        if (hasBuzzer) sb.AppendLine("GPIO.setup(BUZZER_PIN, GPIO.OUT, initial=GPIO.LOW)");
        if (hasServo)  sb.AppendLine("GPIO.setup(SERVO_PIN,  GPIO.OUT, initial=GPIO.LOW)");
        sb.AppendLine();

        // ── Helper functions ─────────────────────────────────────────────────
        if (hasLed)
        {
            sb.AppendLine("# ── Helpers ────────────────────────────────────────────────");
            sb.AppendLine("def blink(times=3, delay=0.5):");
            sb.AppendLine("    for _ in range(times):");
            sb.AppendLine("        GPIO.output(LED_PIN, GPIO.HIGH)");
            sb.AppendLine("        time.sleep(delay)");
            sb.AppendLine("        GPIO.output(LED_PIN, GPIO.LOW)");
            sb.AppendLine("        time.sleep(delay)");
            sb.AppendLine();
        }
        if (hasBuzzer)
        {
            if (!hasLed) sb.AppendLine("# ── Helpers ────────────────────────────────────────────────");
            sb.AppendLine("def beep(times=1, duration=0.1):");
            sb.AppendLine("    for _ in range(times):");
            sb.AppendLine("        GPIO.output(BUZZER_PIN, GPIO.HIGH)");
            sb.AppendLine("        time.sleep(duration)");
            sb.AppendLine("        GPIO.output(BUZZER_PIN, GPIO.LOW)");
            sb.AppendLine("        time.sleep(0.05)");
            sb.AppendLine();
        }

        // ── Main loop ────────────────────────────────────────────────────────
        sb.AppendLine("# ── Main loop ──────────────────────────────────────────────");
        sb.AppendLine("print('StemFlow Lab started. Nhấn Ctrl+C để dừng.')");
        sb.AppendLine("try:");
        sb.AppendLine("    while True:");

        bool hasActiveBody = false;

        // Button → LED (ưu tiên interactive hơn blink đơn giản)
        if (hasButton && hasLed)
        {
            sb.AppendLine("        btn = GPIO.input(BTN_PIN)");
            sb.AppendLine("        if btn == GPIO.HIGH:");
            sb.AppendLine("            print('Button pressed → LED ON')");
            sb.AppendLine("            GPIO.output(LED_PIN, GPIO.HIGH)");
            sb.AppendLine("        else:");
            sb.AppendLine("            GPIO.output(LED_PIN, GPIO.LOW)");
            hasActiveBody = true;
        }
        else if (hasLed)
        {
            sb.AppendLine("        blink(times=1, delay=0.5)");
            hasActiveBody = true;
        }

        // DHT sensor read
        if (hasDht)
        {
            sb.AppendLine("        humidity, temperature = Adafruit_DHT.read_retry(DHT_SENSOR, DHT_PIN)");
            sb.AppendLine("        if humidity is not None:");
            sb.AppendLine("            print(f'  Nhiệt độ: {temperature:.1f}°C  Độ ẩm: {humidity:.1f}%')");
            if (hasLcd)
                sb.AppendLine("            lcd.write_string(f'T:{temperature:.1f}C H:{humidity:.1f}%')");
            sb.AppendLine("        else:");
            sb.AppendLine("            print('  DHT đọc thất bại, thử lại...')");
            hasActiveBody = true;
        }

        // Buzzer (độc lập hoặc kết hợp button)
        if (hasBuzzer && hasButton && !hasLed)
        {
            sb.AppendLine("        if GPIO.input(BTN_PIN) == GPIO.HIGH:");
            sb.AppendLine("            print('Button pressed → Beep!')");
            sb.AppendLine("            beep(times=2)");
            hasActiveBody = true;
        }
        else if (hasBuzzer && !hasButton)
        {
            sb.AppendLine("        beep(times=1)");
            hasActiveBody = true;
        }

        // Potentiometer mock
        if (hasPot)
        {
            sb.AppendLine("        pot_value = random.randint(0, 1023)   # mock ADC read");
            sb.AppendLine("        print(f'  Potentiometer: {pot_value}/1023')");
            hasActiveBody = true;
        }

        // Servo sweep
        if (hasServo)
        {
            sb.AppendLine("        for angle in [0, 90, 180, 90, 0]:   # mock PWM sweep");
            sb.AppendLine("            print(f'  Servo → {angle}°')");
            sb.AppendLine("            time.sleep(0.3)");
            hasActiveBody = true;
        }

        if (!hasActiveBody)
        {
            sb.AppendLine("        # Không phát hiện I/O component tích cực trong diagram.");
            sb.AppendLine("        print('Diagram đang chạy (passive components only)')");
        }

        sb.AppendLine("        time.sleep(1)");
        sb.AppendLine();
        sb.AppendLine("except KeyboardInterrupt:");
        sb.AppendLine("    print('Dừng lab.')");
        sb.AppendLine("    GPIO.cleanup()");

        return sb.ToString();
    }

    // ── Catalog ───────────────────────────────────────────────────────────────

    public IEnumerable<ComponentMeta> GetAllComponents() => _catalog.Values;

    // ── Private: Build catalog ────────────────────────────────────────────────

    private static Dictionary<string, ComponentMeta> BuildCatalog() => new()
    {
        ["wokwi-arduino-uno"] = new ComponentMeta
        {
            Type = "wokwi-arduino-uno",
            Label = "Arduino Uno",
            Description = "Arduino Uno board.",
            Pins = new List<string> { "GND.1","GND.2","5V","3.3V","VIN","D0","D1","D2","D3","D4","D5","D6","D7","D8","D9","D10","D11","D12","D13","A0","A1","A2","A3","A4","A5" },
            GpioPins = new List<string>(),
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-arduino-mega"] = new ComponentMeta
        {
            Type = "wokwi-arduino-mega",
            Label = "Arduino Mega 2560",
            Description = "Arduino Mega board.",
            Pins = new List<string> { "5V", "3.3V", "GND", "D2", "D3", "D4", "D5", "D13", "A0", "A1" },
            GpioPins = new List<string>(),
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-arduino-nano"] = new ComponentMeta
        {
            Type = "wokwi-arduino-nano",
            Label = "Arduino Nano",
            Description = "Arduino Nano board.",
            Pins = new List<string> { "5V", "3.3V", "GND", "D2", "D3", "D4", "D13", "A0", "A1" },
            GpioPins = new List<string>(),
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-esp32"] = new ComponentMeta
        {
            Type = "wokwi-esp32",
            Label = "ESP32 DevKit",
            Description = "ESP32 development board.",
            Pins = new List<string> { "3V3", "5V", "GND", "GPIO2", "GPIO4", "GPIO5", "GPIO18", "GPIO19", "GPIO21", "GPIO22", "GPIO23" },
            GpioPins = new List<string>(),
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-pi-pico"] = new ComponentMeta
        {
            Type = "wokwi-pi-pico",
            Label = "Raspberry Pi Pico",
            Description = "RP2040 development board.",
            Pins = new List<string> { "3V3", "VBUS", "GND", "GP0", "GP1", "GP2", "GP3", "GP4", "GP5" },
            GpioPins = new List<string>(),
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-attiny85"] = new ComponentMeta
        {
            Type = "wokwi-attiny85",
            Label = "ATtiny85",
            Description = "ATtiny85 microcontroller.",
            Pins = new List<string> { "PB0", "PB1", "PB2", "PB3", "PB4", "GND", "VCC" },
            GpioPins = new List<string>(),
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-led"] = new ComponentMeta
        {
            Type         = "wokwi-led",
            Label        = "LED",
            Description  = "Đèn LED đơn sắc, bật/tắt qua GPIO OUTPUT.",
            Pins         = new List<string> { "A", "C" },
            GpioPins     = new List<string> { "A" },
            DefaultAttrs = new Dictionary<string, string> { ["color"] = "red" }
        },

        ["wokwi-rgb-led"] = new ComponentMeta
        {
            Type = "wokwi-rgb-led",
            Label = "RGB LED",
            Description = "RGB LED.",
            Pins = new List<string> { "R", "G", "B", "COM" },
            GpioPins = new List<string> { "R", "G", "B" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-pushbutton"] = new ComponentMeta
        {
            Type         = "wokwi-pushbutton",
            Label        = "Push Button",
            Description  = "Nút nhấn tạm thời, đọc trạng thái HIGH/LOW qua GPIO INPUT.",
            Pins         = new List<string> { "1.l", "2.l", "1.r", "2.r" },
            GpioPins     = new List<string> { "1.l" },
            DefaultAttrs = new Dictionary<string, string> { ["color"] = "green" }
        },

        ["wokwi-resistor"] = new ComponentMeta
        {
            Type         = "wokwi-resistor",
            Label        = "Resistor",
            Description  = "Điện trở giới hạn dòng. Passive — không cần điều khiển GPIO.",
            Pins         = new List<string> { "1", "2" },
            GpioPins     = new List<string>(),
            DefaultAttrs = new Dictionary<string, string> { ["value"] = "220" }
        },

        ["wokwi-dht22"] = new ComponentMeta
        {
            Type         = "wokwi-dht22",
            Label        = "DHT22 Sensor",
            Description  = "Cảm biến nhiệt độ & độ ẩm chính xác cao. Mock bằng Adafruit_DHT.",
            Pins         = new List<string> { "VCC", "SDA", "NC", "GND" },
            GpioPins     = new List<string> { "SDA" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-dht11"] = new ComponentMeta
        {
            Type         = "wokwi-dht11",
            Label        = "DHT11 Sensor",
            Description  = "Cảm biến nhiệt độ & độ ẩm cơ bản. Mock bằng Adafruit_DHT.",
            Pins         = new List<string> { "VCC", "SDA", "NC", "GND" },
            GpioPins     = new List<string> { "SDA" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-buzzer"] = new ComponentMeta
        {
            Type         = "wokwi-buzzer",
            Label        = "Buzzer",
            Description  = "Còi điện tử, phát âm thanh khi GPIO HIGH.",
            Pins         = new List<string> { "1", "2" },
            GpioPins     = new List<string> { "1" },
            DefaultAttrs = new Dictionary<string, string> { ["volume"] = "0.5" }
        },

        ["wokwi-lcd1602"] = new ComponentMeta
        {
            Type         = "wokwi-lcd1602",
            Label        = "LCD 16×2",
            Description  = "Màn hình LCD 16 cột 2 hàng, hiển thị text qua mock _LCD.",
            Pins         = new List<string>
                           { "VSS","VDD","V0","RS","RW","E","D0","D1","D2","D3","D4","D5","D6","D7","A","K" },
            GpioPins     = new List<string> { "RS", "E", "D4", "D5", "D6", "D7" },
            DefaultAttrs = new Dictionary<string, string>
            {
                ["background"] = "blue",
                ["color"]      = "white"
            }
        },

        ["wokwi-lcd2004"] = new ComponentMeta
        {
            Type = "wokwi-lcd2004",
            Label = "LCD 20x4",
            Description = "LCD 20x4 display.",
            Pins = new List<string> { "VSS", "VDD", "SDA", "SCL", "A", "K" },
            GpioPins = new List<string> { "SDA", "SCL" },
            DefaultAttrs = new Dictionary<string, string> { ["background"] = "blue", ["color"] = "white" }
        },

        ["wokwi-ssd1306"] = new ComponentMeta
        {
            Type = "wokwi-ssd1306",
            Label = "OLED 128x64",
            Description = "SSD1306 OLED display.",
            Pins = new List<string> { "GND", "VCC", "SCL", "SDA" },
            GpioPins = new List<string> { "SCL", "SDA" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-max7219-matrix"] = new ComponentMeta
        {
            Type = "wokwi-max7219-matrix",
            Label = "LED Matrix 8x8",
            Description = "MAX7219 LED matrix.",
            Pins = new List<string> { "VCC", "GND", "DIN", "CS", "CLK" },
            GpioPins = new List<string> { "DIN", "CS", "CLK" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-potentiometer"] = new ComponentMeta
        {
            Type         = "wokwi-potentiometer",
            Label        = "Potentiometer",
            Description  = "Biến trở đọc giá trị analog. Cần ADC để dùng với GPIO digital (mock random).",
            Pins         = new List<string> { "GND", "SIG", "VCC" },
            GpioPins     = new List<string> { "SIG" },
            DefaultAttrs = new Dictionary<string, string> { ["value"] = "0" }
        },

        ["wokwi-slide-switch"] = new ComponentMeta
        {
            Type = "wokwi-slide-switch",
            Label = "Slide Switch",
            Description = "Slide switch.",
            Pins = new List<string> { "1", "2", "3" },
            GpioPins = new List<string> { "2" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-keypad"] = new ComponentMeta
        {
            Type = "wokwi-keypad",
            Label = "Keypad",
            Description = "Matrix keypad.",
            Pins = new List<string> { "R1", "R2", "R3", "R4", "C1", "C2", "C3", "C4" },
            GpioPins = new List<string> { "R1", "R2", "R3", "R4", "C1", "C2", "C3", "C4" },
            DefaultAttrs = new Dictionary<string, string> { ["columns"] = "4" }
        },

        ["wokwi-capacitor"] = new ComponentMeta
        {
            Type = "wokwi-capacitor",
            Label = "Capacitor",
            Description = "Capacitor.",
            Pins = new List<string> { "1", "2" },
            GpioPins = new List<string>(),
            DefaultAttrs = new Dictionary<string, string> { ["capacitance"] = "100e-6" }
        },

        ["wokwi-hc-sr04"] = new ComponentMeta
        {
            Type = "wokwi-hc-sr04",
            Label = "HC-SR04",
            Description = "Ultrasonic distance sensor.",
            Pins = new List<string> { "VCC", "TRIG", "ECHO", "GND" },
            GpioPins = new List<string> { "TRIG", "ECHO" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-pir-motion-sensor"] = new ComponentMeta
        {
            Type = "wokwi-pir-motion-sensor",
            Label = "PIR Motion Sensor",
            Description = "PIR motion sensor.",
            Pins = new List<string> { "VCC", "OUT", "GND" },
            GpioPins = new List<string> { "OUT" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-mpu6050"] = new ComponentMeta
        {
            Type = "wokwi-mpu6050",
            Label = "MPU-6050",
            Description = "Accelerometer and gyroscope.",
            Pins = new List<string> { "VCC", "GND", "SCL", "SDA" },
            GpioPins = new List<string> { "SCL", "SDA" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-photoresistor-sensor"] = new ComponentMeta
        {
            Type = "wokwi-photoresistor-sensor",
            Label = "Photoresistor Sensor",
            Description = "Light sensor.",
            Pins = new List<string> { "VCC", "GND", "AO", "DO" },
            GpioPins = new List<string> { "AO", "DO" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-ds18b20"] = new ComponentMeta
        {
            Type = "wokwi-ds18b20",
            Label = "DS18B20",
            Description = "One-wire temperature sensor.",
            Pins = new List<string> { "GND", "DQ", "VDD" },
            GpioPins = new List<string> { "DQ" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-servo"] = new ComponentMeta
        {
            Type         = "wokwi-servo",
            Label        = "Servo Motor",
            Description  = "Động cơ servo điều khiển góc quay qua PWM (mock sweep 0°→180°).",
            Pins         = new List<string> { "GND", "V+", "PWM" },
            GpioPins     = new List<string> { "PWM" },
            DefaultAttrs = new Dictionary<string, string> { ["horn"] = "cross" }
        },

        ["wokwi-stepper-motor"] = new ComponentMeta
        {
            Type = "wokwi-stepper-motor",
            Label = "Stepper Motor",
            Description = "Stepper motor.",
            Pins = new List<string> { "A+", "A-", "B+", "B-" },
            GpioPins = new List<string> { "A+", "A-", "B+", "B-" },
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-5v"] = new ComponentMeta
        {
            Type = "wokwi-5v",
            Label = "5V Supply",
            Description = "5V power source.",
            Pins = new List<string> { "5V" },
            GpioPins = new List<string>(),
            DefaultAttrs = new Dictionary<string, string>()
        },

        ["wokwi-gnd"] = new ComponentMeta
        {
            Type = "wokwi-gnd",
            Label = "Ground",
            Description = "Ground terminal.",
            Pins = new List<string> { "GND" },
            GpioPins = new List<string>(),
            DefaultAttrs = new Dictionary<string, string>()
        }
    };
}
